security: 


    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
        # used to reload user from session & other features (e.g. switch_user)
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\LoginAuthenticator
            logout:
                path: app_logout
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800 # 1 week in seconds

    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/register, roles: PUBLIC_ACCESS }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/dashboard, roles: ROLE_USER }
        - { path: ^/, roles: ROLE_USER }
        - { path: ^/user, roles: ROLE_SUPER_ADMIN }
        - { path: ^/news, roles: ROLE_NEWS_ENTRY }
        - { path: ^/api, roles: ROLE_USER }

    role_hierarchy:
        ROLE_SUPER_ADMIN:       
            - ROLE_ADMIN
            - ROLE_NEWS_ENTRY
        ROLE_ADMIN:             
            - ROLE_NEWS_ENTRY   